name: Terraform Validate
on:
  pull_request:
    branches: [main]
jobs:
  cli-validations:
    runs-on: ubuntu-latest
    name: Terraform cli validations
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform format
        run: terraform fmt --recursive
      - name: Terraform Validate Module
        run: |
          terraform init -backend=false
          terraform validate ./
      - name: Terraform Validate Examples
        working-directory: examples/complete
        run: |
          terraform init -backend=false
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.567.0

